# Generated by Django 4.0.6 on 2022-08-09 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardReport',
            fields=[
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='creditcardrep.uploadedfile')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prop_id', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=2)),
                ('account', models.CharField(max_length=10)),
                ('last_four', models.CharField(max_length=4)),
                ('user', models.CharField(max_length=8)),
                ('vendor_id', models.CharField(max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditcardrep.creditcardreport')),
            ],
        ),
    ]
