# Generated by Django 4.0.6 on 2022-08-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditcardrep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardreport',
            name='date',
        ),
    ]
