# Generated by Django 4.0.6 on 2022-07-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRecapSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=7)),
                ('octxci', models.DecimalField(decimal_places=2, max_digits=6)),
                ('octxst', models.DecimalField(decimal_places=2, max_digits=6)),
                ('saletx', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
